# Generated by Django 4.2 on 2026-06-18 09:56

from django.db import migrations, models
import django.db.models.deletion

from django.db import migrations
from django.contrib.auth import get_user_model

def create_superuser(apps, schema_editor):
    User = get_user_model()

    if not User.objects.filter(username="admin1").exists():
        User.objects.create_superuser(
            username="admin1",
            email="admin@example.com",
            password="admin1"
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', 'previous_migration'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('townhall', 'Town Hall Meeting'), ('launch', 'Official Launch Event'), ('hackathon', 'Hackathon'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('theme', models.CharField(blank=True, max_length=200)),
                ('prize_info', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='HackathonTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('team_leader_name', models.CharField(max_length=200)),
                ('team_leader_email', models.EmailField(max_length=254)),
                ('team_leader_phone', models.CharField(blank=True, max_length=50)),
                ('skills', models.TextField(blank=True)),
                ('project_category', models.CharField(blank=True, max_length=200)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_teams', to='core.event')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_name', models.CharField(default='Digital Hub', max_length=200)),
                ('tagline', models.CharField(default='Innovate. Connect. Transform.', max_length=300)),
                ('launch_date', models.DateTimeField(blank=True, null=True)),
                ('about_mission', models.TextField(blank=True)),
                ('about_vision', models.TextField(blank=True)),
                ('about_objectives', models.TextField(blank=True)),
                ('about_impact', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_address', models.TextField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.hackathonteam')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsors/')),
                ('website_url', models.URLField(blank=True)),
                ('tier', models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('partner', 'Partner')], default='partner', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='core.event')),
            ],
            options={
                'ordering': ['tier', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('biography', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='speakers/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='core.event')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('area_of_interest', models.CharField(blank=True, max_length=200)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.event')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('activity', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='core.event')),
            ],
            options={
                'ordering': ['order', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('event', 'Event Update'), ('venue', 'Venue Change'), ('speaker', 'Speaker Announcement'), ('hackathon', 'Hackathon Update'), ('winner', 'Winner Announcement')], default='general', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='core.event')),
            ],
            options={
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('event', 'email'), name='unique_registration_per_event'),
        ),
        migrations.AddConstraint(
            model_name='hackathonteam',
            constraint=models.UniqueConstraint(fields=('event', 'team_leader_email'), name='unique_team_per_event'),
        ),
    ]
