# Generated by Django 4.2 on 2026-06-16 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('townhall', 'Town Hall Meeting'), ('launch', 'Official Launch Event'), ('hackathon', 'Hackathon'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('theme', models.CharField(blank=True, max_length=200)),
                ('prize_info', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_name', models.CharField(default='Digital Hub', max_length=200)),
                ('tagline', models.CharField(default='Innovate. Connect. Transform.', max_length=300)),
                ('launch_date', models.DateTimeField(blank=True, null=True)),
                ('about_mission', models.TextField(blank=True)),
                ('about_vision', models.TextField(blank=True)),
                ('about_objectives', models.TextField(blank=True)),
                ('about_impact', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_address', models.TextField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('area_of_interest', models.CharField(blank=True, max_length=200)),
                ('team_name', models.CharField(blank=True, max_length=200)),
                ('skills', models.TextField(blank=True)),
                ('project_category', models.CharField(blank=True, max_length=200)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.event')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('event', 'Event Update'), ('venue', 'Venue Change'), ('speaker', 'Speaker Announcement'), ('hackathon', 'Hackathon Update'), ('winner', 'Winner Announcement')], default='general', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='core.event')),
            ],
            options={
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
    ]
