# Generated by Django 4.2 on 2026-06-17 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('team_leader_name', models.CharField(max_length=200)),
                ('team_leader_email', models.EmailField(max_length=254)),
                ('team_leader_phone', models.CharField(blank=True, max_length=50)),
                ('skills', models.TextField(blank=True)),
                ('project_category', models.CharField(blank=True, max_length=200)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-registered_at']},
        ),
        migrations.RemoveField(
            model_name='registration',
            name='project_category',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='team_name',
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('event', 'email'), name='unique_registration_per_event'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.hackathonteam'),
        ),
        migrations.AddField(
            model_name='hackathonteam',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_teams', to='core.event'),
        ),
        migrations.AddConstraint(
            model_name='hackathonteam',
            constraint=models.UniqueConstraint(fields=('event', 'team_leader_email'), name='unique_team_per_event'),
        ),
    ]
